# choose an images
FROM ubuntu

# Install nodejs
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

# Copy code to image
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY index.js index.js

# run command to install node_modules directory
RUN npm install


# Run the Image
ENTRYPOINT [ "node", "index.js" ]

